name = 'Labrador'
license = 'MIT'
licenselink = 'https://github.com/guangmean/Labrador/blob/master/LICENSE'
description = 'Labrador - Pets Theme for Hugo'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/guangmean/Labrador'

# If you have a running demo of the theme
demosite = 'https://www.labradorpal.com'

# Taxonomy terms
tags = ['blog', 'company']
features = ['responsive', 'modern', 'minimal', 'personal', 'clean', 'classic', 'pets', 'i18n', 'multiple language']

# If the theme has multiple authors
#authors = [
#  {name = 'Name of author', homepage = 'Website of author'},
#  {name = 'Name of author', homepage = 'Website of author'}
#]

# If the theme has a single author
[author]
  name = 'guangmean'
  homepage = 'https://github.com/guangmean/Labrador'

# If porting an existing theme
#[original]
#  author = 'Name of original author'
#  homepage = 'Website of original author'
#  repo = 'https://github.com/owner/repo'
